import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient({ log: [] });
import { VersionService } from "../src/services/dms/version-service";
import { PdfService } from "../src/services/dms/pdf-service";
import { ApprovalService } from "../src/lib/dms/services/ApprovalService";

async function verifyStructuredAuthoring() {
    console.log("🚀 Starting Structured Authoring Verification [V2]...");

    const tenantId = 1;
    const userId = 1;
    const mockUser = { sub: userId, tenantId, permissions: ["DMS_DOCUMENT_CREATE", "DMS_DOCUMENT_EDIT", "DMS_DOCUMENT_APPROVE"] } as any;

    try {
        // 0. Find an existing folder
        const folder = await prisma.folder.findFirst();
        if (!folder) {
            throw new Error("No folders found in database. Please seed data first.");
        }

        // 1. Create a STRUCTURED document
        console.log("--- Step 1: Create STRUCTURED Document ---");
        const doc = await prisma.document.create({
            data: {
                tenantId,
                title: `Structured Authoring Test ${Date.now()}`,
                description: "Verifying TipTap integration",
                status: "DRAFT",
                createdById: userId,
                folderId: folder.id,
            }
        });
        console.log(`✅ Document created: ${doc.id}`);

        // Diagnostic: Check if any versions exist for this new ID
        const existingVersions = await prisma.documentVersion.findMany({ where: { documentId: doc.id } });
        console.log(`[DIAGNOSTIC] Versions found for new doc ${doc.id}: ${existingVersions.length}`);
        if (existingVersions.length > 0) {
            console.log("[DIAGNOSTIC] EXTREMELY WEIRD: Versions found for a brand new document!", existingVersions);
        }

        // 2. Save structured content (Simulate TipTap JSON)
        console.log("--- Step 2: Save Structured Content ---");
        const tipTapJson = {
            type: "doc",
            content: [
                {
                    type: "heading",
                    attrs: { level: 1 },
                    content: [{ type: "text", text: "Structured Content Verification" }]
                },
                {
                    type: "paragraph",
                    content: [{ type: "text", text: "This content was generated by a automated test script simulating TipTap." }]
                }
            ]
        };

        console.log("[DEBUG-STEP] Preparing to call saveStructuredVersion...");
        const version = await VersionService.saveStructuredVersion({
            tenantId,
            documentId: doc.id,
            contentJson: tipTapJson,
            user: mockUser
        });
        console.log("[DEBUG-STEP] saveStructuredVersion call completed.");
        console.log(`✅ Version created: ${version.versionNumber} (Mode: ${version.contentMode})`);

        if (version.contentMode !== "STRUCTURED") {
            throw new Error(`Expected contentMode STRUCTURED, got ${version.contentMode}`);
        }

        // 3. Verify content preservation
        console.log("--- Step 3: Verify Content Preservation ---");
        const fetchedVersion = await prisma.documentVersion.findUnique({ where: { id: version.id } }) as any;
        if (fetchedVersion?.contentJson?.type !== tipTapJson.type) {
            console.error("JSON mismatch! Expected type 'doc'", fetchedVersion?.contentJson);
            throw new Error("Content JSON mismatch!");
        }
        console.log("✅ Content JSON verified (Basic structure matches).");

        // 4. Simulate Approval & PDF Generation
        console.log("--- Step 4: Finalize Approval & PDF Generation ---");
        // We need to update the doc pointer manually if not using the full workflow engine for this test
        await prisma.document.update({
            where: { id: doc.id },
            data: { currentVersionId: version.id }
        });

        const approvalResult = await ApprovalService.finalizeDocumentApproval(
            prisma,
            doc.id,
            tenantId,
            userId
        );
        console.log("✅ Document Approved.");

        // 5. Check if PDF Key exists
        const approvedVersion = await prisma.documentVersion.findUnique({ where: { id: version.id } });
        console.log(`✅ Generated PDF Key: ${approvedVersion?.storageKey}`);
        if (!approvedVersion?.storageKey?.includes("generated.pdf")) {
            throw new Error("PDF Snapshot key not found or incorrect format!");
        }

        console.log("\n✨ Verification PASSED!");
    } catch (error: any) {
        console.error("\n❌ Verification FAILED!");
        console.error(`ERROR [${error.name || 'Error'}]: ${error.message}`);
        if (error.stack && error.stack.includes('playwright')) {
            console.error("TIP: Playwright might not be installed. Run 'npx playwright install chromium'");
        }
        process.exit(1);
    }
}

verifyStructuredAuthoring();
